# config.py - MINIMAL WORKING VERSION
import os

# Get from environment variables (set in Render dashboard)
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER") 
PATIENT_PHONE_NUMBER = os.getenv("PATIENT_PHONE_NUMBER")

# Critical settings
USE_SMS_ONLY = True  # MUST be True during WhatsApp limit

if not all([TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER, PATIENT_PHONE_NUMBER]):
    print("❌ MISSING TWILIO CREDENTIALS - SET IN RENDER DASHBOARD")SE_SMS_ONLY}")
